package test.service.impl.activityservice;

import static org.junit.Assert.fail;

import org.junit.Test;

import javastrava.api.v3.model.StravaComment;
import javastrava.api.v3.service.exception.NotFoundException;
import javastrava.api.v3.service.exception.UnauthorizedException;
import javastrava.config.JavastravaApplicationConfig;
import test.api.model.StravaCommentTest;
import test.service.standardtests.CreateMethodTest;
import test.service.standardtests.callbacks.CreateCallback;
import test.service.standardtests.callbacks.DeleteCallback;
import test.service.standardtests.callbacks.GetCallback;
import test.service.standardtests.data.ActivityDataUtils;
import test.service.standardtests.data.CommentDataUtils;
import test.utils.RateLimitedTestRunner;
import test.utils.TestUtils;

/**
 * <p>
 * Tests for methods which allow creation of comments
 * </p>
 *
 * @author Dan Shannon
 *
 */
public class CreateCommentTest extends CreateMethodTest<StravaComment, Integer> {
	@Override
	protected StravaComment generateValidObject() {
		return CommentDataUtils.generateValidObject();
	}

	@Override
	protected StravaComment generateInvalidObject() {
		return CommentDataUtils.generateInvalidObject();
	}

	@Override
	@Test
	public void testCreateValidObject() throws Exception {
		// Can't run the test if we don't have Strava's permission to write comments
		if (JavastravaApplicationConfig.STRAVA_ALLOWS_COMMENTS_WRITE) {

			RateLimitedTestRunner.run(() -> {
				// Create a comment
				final StravaComment comment = generateValidObject();

				// Add to Strava
				final StravaComment createdComment = creator().create(TestUtils.stravaWithFullAccess(), comment);

				// Validate
				StravaCommentTest.validateComment(createdComment);

				// Delete it again
				deleter().delete(TestUtils.stravaWithFullAccess(), createdComment);
			});
		}
	}

	@Override
	@Test
	public void testCreateNonExistentParent() throws Exception {
		// Can't run the test if we don't have Strava's permission to write comments
		if (JavastravaApplicationConfig.STRAVA_ALLOWS_COMMENTS_WRITE) {

			RateLimitedTestRunner.run(() -> {
				// Create a comment
				final StravaComment comment = generateValidObject();

				// Add to Strava
				final StravaComment createdComment;
				try {
					createdComment = creator().create(TestUtils.stravaWithFullAccess(), comment);
				} catch (final NotFoundException e) {
					// Expected
					return;
				}

				// Delete it again and fail
				deleter().delete(TestUtils.stravaWithFullAccess(), createdComment);
				fail("Created a comment against a non-existent parent activity!"); //$NON-NLS-1$
			});
		}
	}

	@Override
	@Test
	public void testInvalidId() throws Exception {
		// Not relevant for create methods - you don't specify the id, it's generated by Strava
		return;

	}

	@Override
	@Test
	public void testPrivateBelongsToOtherUser() throws Exception {
		// Can't run the test if we don't have Strava's permission to write comments
		if (JavastravaApplicationConfig.STRAVA_ALLOWS_COMMENTS_WRITE) {

			RateLimitedTestRunner.run(() -> {
				final StravaComment comment = generateValidObject();
				comment.setActivityId(ActivityDataUtils.ACTIVITY_PRIVATE_OTHER_USER);

				// Attempt to make the comment
				final StravaComment createdComment;
				try {
					createdComment = creator().create(TestUtils.stravaWithFullAccess(), comment);
				} catch (final UnauthorizedException e) {
					// Expected
					return;
				}

				// Delete it again and fail
				deleter().delete(TestUtils.stravaWithFullAccess(), createdComment);
				fail("Created a comment against a private activity belongoing to another user!"); //$NON-NLS-1$
			});
		}
	}

	@Override
	public void testCreateInvalidObject() throws Exception {
		// Can't run the test if we don't have Strava's permission to write comments
		if (JavastravaApplicationConfig.STRAVA_ALLOWS_COMMENTS_WRITE) {

			super.testCreateInvalidObject();
		}
	}

	@Override
	public void testCreateNoWriteAccess() throws Exception {
		// Can't run the test if we don't have Strava's permission to write comments
		if (JavastravaApplicationConfig.STRAVA_ALLOWS_COMMENTS_WRITE) {

			super.testCreateNoWriteAccess();
		}
	}

	@Override
	@Test
	public void testPrivateWithViewPrivateScope() throws Exception {
		// Covered by testCreateValidObject()
		return;

	}

	@Override
	@Test
	public void testPrivateWithNoViewPrivateScope() throws Exception {
		// Can't run the test if we don't have Strava's permission to write comments
		if (JavastravaApplicationConfig.STRAVA_ALLOWS_COMMENTS_WRITE) {

			RateLimitedTestRunner.run(() -> {
				// Create a comment
				final StravaComment comment = generateValidObject();

				// Add to Strava
				final StravaComment createdComment;
				try {
					createdComment = creator().create(TestUtils.stravaWithWriteAccess(), comment);
				} catch (final UnauthorizedException e) {
					// Expected
					return;
				}

				// Delete it again
				deleter().delete(TestUtils.stravaWithFullAccess(), createdComment);
				fail("Created a comment on a private activity, but don't have view_private scope in token"); //$NON-NLS-1$
			});
		}
	}

	@Override
	protected CreateCallback<StravaComment> creator() throws Exception {
		return CommentDataUtils.stravaCreator();
	}

	@Override
	protected DeleteCallback<StravaComment> deleter() throws Exception {
		return CommentDataUtils.deleter();
	}

	@Override
	protected GetCallback<StravaComment, Integer> getter() throws Exception {
		return CommentDataUtils.getter();
	}

	@Override
	protected void validate(StravaComment object) {
		StravaCommentTest.validateComment(object);

	}

}
